controller:
  kind: DaemonSet
  livenessProbe:
    failureThreshold: 10
  readinessProbe:
    failureThreshold: 10
  service:
    type: NodePort
    nodePorts:
      http: 32300
      https: 32301
  config:
    use-forwarded-headers: "true"
